# -*- coding: utf-8 -*-
"""detect_gun_yolov8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mpli1lCHv59W30ajMVAV7-av0xD1why7
"""

!pip install ultralytics

# Download pretrain model Yolov8n - Nhanh
!wget https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt

# Pip install method (recommended)
!pip install ultralytics==8.0.20

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/intern

!ls

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/intern

# Train với CLI
!yolo task=detect mode=train model=yolov8n.pt data=/content/drive/MyDrive/intern/detect_gun_yolov8.yaml \
epochs=100 \
imgsz=640  \
save=True

Image(filename='runs/detect/train14/confusion_matrix.png', width=600)

Image(filename='runs/detect/train14/results.png', width=600)

Image(filename='runs/detect/train14/val_batch0_pred.jpg', width=800)

Image(filename='runs/detect/train14/val_batch1_pred.jpg', width=800)

Image(filename='runs/detect/train14/val_batch2_pred.jpg', width=800)

!yolo task=detect mode=predict model="/content/drive/MyDrive/intern/runs/detect/train14/weights/last.pt" \
source="/content/drive/MyDrive/intern/gun/test/images/image_0_k.jpg"

Image(filename='/content/drive/MyDrive/intern/runs/detect/predict/image_0_k.jpg', width=600)

!yolo task=detect mode=predict model="/content/drive/MyDrive/intern/runs/detect/train14/weights/last.pt" \
source="/content/drive/MyDrive/intern/gun/test/images/image_128_y.jpg"

Image(filename='/content/drive/MyDrive/intern/runs/detect/predict4/image_128_y.jpg', width=600)

!yolo task=detect mode=predict model="/content/drive/MyDrive/intern/runs/detect/train14/weights/last.pt" \
source="/content/drive/MyDrive/intern/gun/test/images/image_26_b.jpg"
Image(filename='/content/drive/MyDrive/intern/runs/detect/predict5/image_26_b.jpg', width=600)

!yolo task=detect mode=predict model=/content/drive/MyDrive/intern/runs/detect/train14/weights/best.pt conf=0.25 \
source=/content/drive/MyDrive/intern/gun/test/images

from ultralytics import YOLO

'''# Load a pretrained YOLOv8n model
model = YOLO('/content/drive/MyDrive/intern/runs/detect/train14/weights/last.pt')
model.tune(data='/content/drive/MyDrive/intern/detect_gun_yolov8.yaml', epochs=20, optimizer='AdamW', imgsz=640, resume=True, save=True)'''

