# -*- coding: utf-8 -*-
"""yolov5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BLX7MsAHybzWT_oJAUjBqYLvV-05ZTxB
"""

from google.colab import drive
drive.mount('/content/drive/', force_remount=True)

# Commented out IPython magic to ensure Python compatibility.
#  %cd /content/drive/MyDrive/intern
 !git clone https://github.com/ultralytics/yolov5

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/intern/yolov5
# %pip install -r requirements.txt  # install

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/intern/yolov5
# %pip install -r requirements.txt  # install

!python train.py --img 640 --batch 2 --epochs 30 --data /content/drive/MyDrive/intern/your_dataset.yaml --cfg ./models/yolov5s.yaml --weights yolov5s.pt

!python detect.py --weights runs/train/exp7/weights/best.pt --img 640 --conf 0.5 --source /content/drive/MyDrive/intern/test/008.jpg

